# 基础配置（IP/密码/分区）

# 网络基础
CONFIG_TARGET_ipq40xx=y
CONFIG_TARGET_IPQ40XX_DEVICE_generic=y

# IP地址
CONFIG_ETHTOOL_PADDR="192.168.6.1"
CONFIG_ETHTOOL_NETMASK="255.255.255.0"

# 分区设置
CONFIG_TARGET_KERNEL_PARTSIZE=128
CONFIG_TARGET_ROOTFS_PARTSIZE=4096

# 空密码登录
CONFIG_PASSWORD_HASH=""
