name: istoreos-OpenWrt

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择编译分支'
        required: true
        default: 'istoreos-24.10'
        type: choice
        options:
          - istoreos-24.10
          - istoreos-23.05
      device:
        description: '选择设备架构'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64
          - r3g
      
      SSH_ACTION:
        description: '启用SSH调试（需要手动确认）'
        required: false 
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true        
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
        
      - name: 检查磁盘空间
        run: df -h

      - name: 检查内存使用情况
        run: free -h
        
      - name: 建立环境
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev make4.1+ perl python3.7+ which grep libc-dev asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 克隆源代码
        run: |
          git clone --depth 1 -b ${{ github.event.inputs.branch }} https://github.com/istoreos/istoreos
          cd openwrt
          # 根据设备架构选择正确的配置文件路径
          if [ "${{ github.event.inputs.device }}" == "x86_64" ]; then
            cp -r ../configs/x86_64/.config .
            cp -r ../configs/x86_64/feeds.conf.default .
          elif [ "${{ github.event.inputs.device }}" == "r3g" ]; then
            cp -r ../configs/r3g/.config .
            cp -r ../configs/r3g/feeds.conf.default .
          fi
      
      - name: 运行diy-part1.sh
        run: |
          cd openwrt
          chmod +x ../diy-part1.sh
          ../diy-part1.sh

      - name: 运行diy-part2.sh
        run: |
          cd openwrt
          chmod +x ../diy-part2.sh  
          ../diy-part2.sh

      - name: SSH远程连接（make menuconfig）
        if: github.event.inputs.SSH_ACTION == 'true'
        uses: mxschmitt/action-tmate@v3
        with:
          run: sleep infinity
      
      - name: 更新feeds和安装依赖
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
            
      - name: 编译固件
        id: compile
        run: |
          cd openwrt
          make V=s -j2 > build.log || { echo 'Build failed'; cat build.log; exit 1; }
        continue-on-error: true

      - name: 上传生成日志
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt/build.log

      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: openwrt-24.10-${{ github.event.inputs.device }}-${{ github.event.inputs.branch }}-${{ github.event.inputs.date }}
          name: OpenWrt Firmware Release openwrt-24.10-${{ github.event.inputs.device }}-${{ github.event.inputs.branch }}-${{ github.event.inputs.date }}
          body: |
            This is a release of OpenWrt firmware for ${{ github.event.inputs.device }} using ${{ github.event.inputs.branch }} branch.
            Build number: ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            openwrt/bin/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
